modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="ather_the_dragon_surge"
version="1.0.0"
displayName="Ather: The Dragon Surge"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="batza, MCreator"

[[dependencies.ather_the_dragon_surge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




